### PR TITLE
Create composer.json

### PR DESCRIPTION
**Pull request by wilfred-arambhan**
Is it possible to add composer.json as the package is not present in packagist.

### CODE REVIEW

**Comment by wilfred-arambhan** [comment]
Is this package in packagist? If not, can we add composer.json?

**Comment by claviska** [comment]
Added now. I didn't accept this PR because the namespace used.

**Comment by wilfred-arambhan** [comment]
Thanks for adding it. Could you create a class instead of calling a function?

**Comment by claviska** [comment]
Don't have the time right now. Maybe later and if there's demand.

**Comment by wilfred-arambhan** [comment]
Okay, I appreciate it. Thanks!

**Pull request closed without merging**
