### PR TITLE
Added autoload section to autoload simple_php_captcha.php

### PR DESCRIPTION
**Pull request by k00ni**
Without that change, you have to manually include *simple-php-captcha.php* in your script. 

With that change, just use "vendor/autoload.php" and it will be included automatically.

### CODE REVIEW

**Comment by claviska** [comment]
I normally don't bother with autoloading unless I'm working with an actual class, but this seems like a harmless and likely helpful change. Thanks.

**Comment by k00ni** [comment]
I was just wondering, why your function wasn't usable until i figured out, that `simple-php-captcha.php` wasn't included by default. But thanks for merging :)

**Comment by acorbi** [comment]
@claviska can you please tag a new release which includes this feature and add it to packagist so autoload is working on the version on https://packagist.org/packages/abeautifulsite/simple-php-captcha?

Thanks

**Comment by claviska** [comment]
Done.

**Pull request merged**
